from fpdf import FPDF
from datetime import datetime
from typing import List
from agent.models import Finding, SeverityLevel


def _s(text: str) -> str:
    """Sanitize teks agar aman untuk font latin-1 FPDF (ganti karakter unicode yang tidak didukung)."""
    replacements = {
        '—': ' - ',   # em dash —
        '–': '-',     # en dash –
        '‘': "'",     # left single quote '
        '’': "'",     # right single quote '
        '“': '"',     # left double quote "
        '”': '"',     # right double quote "
        '…': '...',   # ellipsis …
        '•': '*',     # bullet •
        '·': '*',     # middle dot ·
        '→': '->',    # arrow →
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Hapus karakter yang masih di luar latin-1
    return text.encode('latin-1', errors='replace').decode('latin-1')


class SecurityAuditReport(FPDF):

    def header(self):
        self.set_fill_color(5, 8, 16)
        self.rect(0, 0, 210, 20, 'F')
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(0, 255, 149)
        self.cell(0, 10, '  OWASP SECURITY AUDIT AGENT - REPORT', align='L', ln=True)
        self.set_draw_color(0, 255, 149)
        self.line(10, 20, 200, 20)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(100, 100, 120)
        self.cell(0, 10, f'Generated by OWASP Security Audit Agent  |  Page {self.page_no()}', align='C')

    def cover_page(self, filename: str, total: int, critical: int, high: int, medium: int, low: int):
        self.add_page()
        self.set_fill_color(5, 8, 16)
        self.rect(0, 0, 210, 297, 'F')

        # Title
        self.ln(20)
        self.set_font('Helvetica', 'B', 28)
        self.set_text_color(0, 255, 149)
        self.cell(0, 14, 'SECURITY AUDIT REPORT', align='C', ln=True)

        self.set_font('Helvetica', '', 12)
        self.set_text_color(100, 116, 139)
        self.cell(0, 8, 'OWASP Top 10 : 2025  |  Python Static Analysis', align='C', ln=True)

        # Divider
        self.ln(5)
        self.set_draw_color(0, 255, 149)
        self.set_line_width(0.5)
        self.line(40, self.get_y(), 170, self.get_y())
        self.ln(10)

        # File info
        self.set_font('Helvetica', '', 11)
        self.set_text_color(148, 163, 184)
        self.cell(0, 7, _s(f'File Diaudit  :  {filename}'), align='C', ln=True)
        self.cell(0, 7, f'Tanggal Audit :  {datetime.now().strftime("%d %B %Y, %H:%M")}', align='C', ln=True)
        self.ln(15)

        # Metrics boxes
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, f'Total Vulnerability Ditemukan: {total}', align='C', ln=True)
        self.ln(8)

        colors = [
            (239, 68, 68, 'CRITICAL', critical),
            (249, 115, 22, 'HIGH', high),
            (234, 179, 8, 'MEDIUM', medium),
            (34, 197, 94, 'LOW', low),
        ]
        box_w, box_h = 38, 28
        start_x = (210 - (box_w * 4 + 6 * 3)) / 2
        y = self.get_y()

        for i, (r, g, b, label, count) in enumerate(colors):
            x = start_x + i * (box_w + 6)
            self.set_fill_color(r // 6, g // 6, b // 6)
            self.rect(x, y, box_w, box_h, 'F')
            self.set_draw_color(r, g, b)
            self.set_line_width(0.8)
            self.rect(x, y, box_w, box_h)
            self.set_font('Helvetica', 'B', 20)
            self.set_text_color(r, g, b)
            self.set_xy(x, y + 4)
            self.cell(box_w, 10, str(count), align='C')
            self.set_font('Helvetica', '', 7)
            self.set_text_color(200, 200, 200)
            self.set_xy(x, y + 17)
            self.cell(box_w, 6, label, align='C')

        self.ln(box_h + 15)

        # Framework info
        self.set_draw_color(30, 41, 59)
        self.set_line_width(0.3)
        self.set_fill_color(7, 12, 24)
        self.rect(30, self.get_y(), 150, 30, 'FD')
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(0, 255, 149)
        self.set_xy(30, self.get_y() + 5)
        self.cell(150, 6, 'POWERED BY', align='C', ln=True)
        self.set_font('Helvetica', '', 8)
        self.set_text_color(148, 163, 184)
        self.set_x(30)
        self.cell(150, 5, 'LangGraph  +  Groq Llama 3.1  +  Rule-Based Auto Fix', align='C', ln=True)
        self.set_x(30)
        self.cell(150, 5, 'OWASP Top 10 : 2025  |  10 Active Checkers', align='C', ln=True)

    def summary_section(self, summary: str):
        self.add_page()
        self._section_title('01', 'AI EXECUTIVE SUMMARY')
        self.set_fill_color(7, 12, 24)
        self.set_draw_color(14, 165, 233)
        self.set_line_width(0.3)
        self.rect(10, self.get_y(), 190, max(30, len(summary) // 3), 'FD')
        self.set_xy(14, self.get_y() + 4)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(125, 211, 252)
        self.multi_cell(182, 6, _s(summary))
        self.ln(5)

    def findings_section(self, findings: List[Finding]):
        self._section_title('02', f'DETAIL FINDINGS  [{len(findings)} VULNERABILITY]')

        severity_colors = {
            SeverityLevel.CRITICAL: (239, 68, 68),
            SeverityLevel.HIGH:     (249, 115, 22),
            SeverityLevel.MEDIUM:   (234, 179, 8),
            SeverityLevel.LOW:      (34, 197, 94),
        }

        for i, f in enumerate(findings, 1):
            if self.get_y() > 250:
                self.add_page()

            r, g, b = severity_colors.get(f.severity, (100, 100, 100))

            # Card background
            card_y = self.get_y()
            self.set_fill_color(7, 12, 24)
            self.rect(10, card_y, 190, 38, 'F')

            # Severity bar
            self.set_fill_color(r, g, b)
            self.rect(10, card_y, 2, 38, 'F')

            # Number
            self.set_font('Helvetica', 'B', 9)
            self.set_text_color(r, g, b)
            self.set_xy(15, card_y + 3)
            self.cell(12, 5, f'#{i:02d}')

            # Severity badge
            self.set_fill_color(r // 5, g // 5, b // 5)
            self.rect(27, card_y + 2, 22, 6, 'F')
            self.set_font('Helvetica', 'B', 7)
            self.set_text_color(r, g, b)
            self.set_xy(27, card_y + 3)
            self.cell(22, 5, f.severity.value, align='C')

            # OWASP category
            self.set_font('Helvetica', '', 7)
            self.set_text_color(100, 116, 139)
            self.set_xy(52, card_y + 3)
            self.cell(80, 5, _s(f.owasp_category.value))

            # Line number
            self.set_xy(150, card_y + 3)
            self.cell(50, 5, f'Line: {f.line_number}', align='R')

            # Title
            self.set_font('Helvetica', 'B', 10)
            self.set_text_color(226, 232, 240)
            self.set_xy(15, card_y + 10)
            self.cell(185, 5, _s(f.title[:80]))

            # Description
            self.set_font('Helvetica', '', 8)
            self.set_text_color(148, 163, 184)
            self.set_xy(15, card_y + 17)
            self.multi_cell(183, 4.5, _s(f.description[:120]))

            # Recommendation
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(14, 165, 233)
            rec_y = min(self.get_y(), card_y + 28)
            self.set_xy(15, rec_y)
            self.cell(8, 4, '>')
            self.multi_cell(178, 4, _s(f.recommendation[:120]))

            self.set_draw_color(30, 41, 59)
            self.set_line_width(0.2)
            self.line(10, card_y + 38, 200, card_y + 38)
            self.set_y(card_y + 40)

    def fixed_code_section(self, fixed_code: str):
        self.add_page()
        self._section_title('03', 'AUTO-FIXED CODE')

        self.set_font('Helvetica', '', 9)
        self.set_text_color(148, 163, 184)
        self.multi_cell(190, 5, 'Kode berikut telah diperbaiki secara otomatis menggunakan Rule-Based Fixer. Setiap perubahan ditandai dengan komentar # FIXED.')
        self.ln(3)

        self.set_fill_color(7, 12, 24)
        self.set_draw_color(30, 41, 59)
        self.rect(10, self.get_y(), 190, 5, 'F')
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(0, 255, 149)
        self.set_xy(14, self.get_y() + 1)
        self.cell(0, 3, 'fixed_code.py')
        self.ln(7)

        self.set_fill_color(13, 17, 23)
        code_y = self.get_y()
        lines = fixed_code.split('\n')[:60]
        block_h = len(lines) * 4.5 + 6
        self.rect(10, code_y, 190, min(block_h, 220), 'F')
        self.set_xy(13, code_y + 3)

        for line in lines:
            if self.get_y() > 270:
                break
            safe_line = _s(line[:100])
            if '# FIXED' in line:
                self.set_text_color(0, 255, 149)
            elif line.strip().startswith('#'):
                self.set_text_color(100, 116, 139)
            elif any(kw in line for kw in ['def ', 'class ', 'import ', 'from ']):
                self.set_text_color(139, 92, 246)
            else:
                self.set_text_color(200, 210, 220)
            self.set_font('Courier', '', 7.5)
            self.set_x(13)
            self.cell(0, 4.5, safe_line, ln=True)

    def _section_title(self, num: str, title: str):
        self.set_fill_color(5, 8, 16)
        self.rect(10, self.get_y(), 190, 10, 'F')
        self.set_draw_color(0, 255, 149)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 10, self.get_y() + 10)
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(0, 255, 149)
        self.set_xy(14, self.get_y() + 2)
        self.cell(10, 6, num)
        self.set_text_color(226, 232, 240)
        self.cell(0, 6, _s(title))
        self.ln(14)


def generate_pdf(filename: str, findings: List[Finding], summary: str, fixed_code: str) -> bytes:
    """Generate PDF report dan return sebagai bytes."""
    pdf = SecurityAuditReport()
    pdf.set_auto_page_break(auto=True, margin=18)

    critical = sum(1 for f in findings if f.severity == SeverityLevel.CRITICAL)
    high     = sum(1 for f in findings if f.severity == SeverityLevel.HIGH)
    medium   = sum(1 for f in findings if f.severity == SeverityLevel.MEDIUM)
    low      = sum(1 for f in findings if f.severity == SeverityLevel.LOW)

    pdf.cover_page(filename, len(findings), critical, high, medium, low)
    pdf.summary_section(summary)

    if findings:
        pdf.findings_section(findings)

    if fixed_code and fixed_code.strip():
        pdf.fixed_code_section(fixed_code)

    return bytes(pdf.output())
